services:
  web:
    container_name: fit-php
    build:
      context: docker
      dockerfile: app.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: fit-psql
    image: postgres:17.0
    restart: always
    environment:
      - "POSTGRES_USER=fit-admin"
      - "POSTGRES_DB=fitness"
      - "POSTGRES_PASSWORD=p4ssw0rd"
    ports:
      - "5441:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app

  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/html

  artisan:
    entrypoint: ["php", "/var/www/html/artisan"]
    build:
      context: docker
      dockerfile: app.Dockerfile
    volumes:
      - ./src:/var/www/html

  pgadmin:
    container_name: fit-pgadmin
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: p4ssw0rd
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 15439:5050
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  web:
  db:
  pgadmin:
